Morus\AcceticBundle\Entity\AcceticConfig:
    type: mappedSuperclass
    table: accetic_config
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        controlCode:
            type: string
            nullable: false
            length: '50'
        value:
            type: text
            nullable: false
        name:
            type: string
            nullable: true
            length: 255
        description:
            type: text
            nullable: true
        sortOrder:
            type: integer
            nullable: true
            column: sort_order
            options:
                unsigned: true
                default: 0
        active:
            type: boolean
            options:
                default: 1
        createDate:
            type: datetime
            column: create_date
        lastModifiedDate:
            type: datetime
            nullable: true
            column: last_modified_date
        inactiveDate:
            type: datetime
            nullable: true
            column: inactive_date
    lifecycleCallbacks:
        prePersist: [ onPrePersist ]
        postPersist: [ onPostPersist ]