Morus\AcceticBundle\Entity\Ap:
    type: mappedSuperclass
    table: accetic_ap
    indexes:
#        IDX_6entity_credit_account:
#            columns:
#                - entity_credit_account
#        IDX_person_id:
#            columns:
#                - person_id
        IDX_unit_id:
            columns:
                - unit_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: AUTO
    fields:
        invnumber:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ' Text identifier for the invoice.  Must be unique.'
        transdate:
            type: date
            nullable: true
            comment: ''
            default: now
        taxincluded:
            type: boolean
            nullable: true
            comment: ''
            default: false
        amount:
            type: decimal
            nullable: true
            precision: 10
            scale: 0
            comment: ' This stores the total amount (including taxes) for the transaction.'
        netamount:
            type: decimal
            nullable: true
            precision: 10
            scale: 0
            comment: ' Total amount excluding taxes for the transaction.'
        paid:
            type: decimal
            nullable: true
            precision: 10
            scale: 0
            comment: ''
        datepaid:
            type: date
            nullable: true
            comment: ''
        duedate:
            type: date
            nullable: true
            comment: ''
        invoice:
            type: boolean
            nullable: true
            comment: " True if the transaction tracks goods/services purchase using the invoice\ntable.  False otherwise."
            default: false
        ordnumber:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ' Order Number'
        curr:
            type: string
            nullable: true
            length: null
            fixed: true
            comment: ' 3 letters to identify the currency.'
        notes:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'These notes are displayed on the invoice when printed or emailed'
        till:
            type: string
            nullable: true
            length: 20
            fixed: false
            comment: ''
        quonumber:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'Quotation Number'
        intnotes:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: "These notes are not displayed when the invoice is printed or emailed and\nmay be updated without reposting hte invocie."
        shipvia:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        languageCode:
            type: string
            nullable: true
            length: 6
            fixed: false
            comment: ''
            column: language_code
        ponumber:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'Purchase Order Number'
        shippingpoint:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        onHold:
            type: boolean
            nullable: true
            comment: ''
            default: false
            column: on_hold
        approved:
            type: boolean
            nullable: true
            comment: 'Only show in financial reports if true.'
            default: true
        reverse:
            type: boolean
            nullable: true
            comment: 'If true numbers are displayed after multiplying by -1'
            default: false
        terms:
            type: smallint
            nullable: true
            unsigned: false
            comment: ''
            default: '0'
        description:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        forceClosed:
            type: boolean
            nullable: true
            comment: " Not exposed to the UI, but can be set to prevent an invoice from showing up\nfor payment or in outstanding reports."
            column: force_closed
        crdate:
            type: date
            nullable: true
            comment: ''
        isReturn:
            type: boolean
            nullable: true
            comment: ''
            default: false
            column: is_return
    manyToOne:
        unit:
            targetEntity: Unit
            cascade: ["persist"]
            inversedBy: aps
            joinColumns:
                unit_id:
                    referencedColumnName: id
            orphanRemoval: false
#        entityCreditAccount:
#            targetEntity: EntityCreditAccount
#            cascade: {  }
#            mappedBy: null
#            inversedBy: null
#            joinColumns:
#                entity_credit_account:
#                    referencedColumnName: id
#            orphanRemoval: false
#        person:
#            targetEntity: EntityEmployee
#            cascade: {  }
#            mappedBy: null
#            inversedBy: null
#            joinColumns:
#                person_id:
#                    referencedColumnName: entity_id
#            orphanRemoval: false
    oneToOne:
        transaction:
            targetEntity: Transaction
            cascade: ["persist"]
            inversedBy: ap
            joinColumns:
                transaction_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks:
        prePersist: [ onPrePersist ]
        postPersist: [ onPostPersist ]
