Morus\AcceticBundle\Entity\C:
    type: mappedSuperclass
    table: accetic_c
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: AUTO
    fields:
        note:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
    manyToOne:
        p:
            targetEntity: P
            cascade: ["persist"]
            inversedBy: cs
            joinColumns:
                c_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: 
        prePersist: [ onPrePersist ]
        postPersist: [ onPostPersist ]
