#   Stores type of contact information attached to companies and persons.
#   Please coordinate with others before adding new types.
Morus\AcceticBundle\Entity\ContactClass:
    type: entity
    table: accetic_contact_class
    uniqueConstraints:
        contact_class_id_key:
            columns:
                - id
                - control_code
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            generator:
                strategy: AUTO
    fields:
        controlCode:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: control_code
        class:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        description:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        sortOrder:
            type: integer
            nullable: true
            column: sort_order
            options:
                unsigned: true
                default: 0
        active:
            type: boolean
            options:
                default: 1
        createDate:
            type: datetime
            column: create_date
        lastModifiedDate:
            type: datetime
            nullable: true
            column: last_modified_date
        inactiveDate:
            type: datetime
            nullable: true
            column: inactive_date
    oneToMany:
        contacts:
            targetEntity: Contact
            mappedBy: contactClass
            orphanRemoval: false
    lifecycleCallbacks: 
        prePersist: [ onPrePersist ]
        postPersist: [ onPostPersist ]
