Morus\AcceticBundle\Entity\InvoiceNote:
    type: mappedSuperclass
    table: accetic_invoice_note
    indexes:
        IDX_entity_id:
            columns:
                - entity_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: AUTO
    fields:
        noteClass:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: note_class
        note:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        subject:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        sortOrder:
            type: integer
            nullable: true
            column: sort_order
            options:
                unsigned: true
                default: 0
        active:
            type: boolean
            options:
                default: 1
        createDate:
            type: datetime
            column: create_date
        lastModifiedDate:
            type: datetime
            nullable: true
            column: last_modified_date
        inactiveDate:
            type: datetime
            nullable: true
            column: inactive_date
    manyToOne:
        invoice:
            targetEntity: Invoice
            cascade: ["persist"]
            inversedBy: invoiceNotes
            joinColumns:
                entity_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: 
        prePersist: [ onPrePersist ]
        postPersist: [ onPostPersist ]
