#Line items of invoices with goods/services attached.
Morus\AcceticBundle\Entity\Invoice:
    type: mappedSuperclass
    table: accetic_invoice
    indexes:
        invoice_trans_id_key:
            columns:
                - transaction_id
        IDX_parts_id:
            columns:
                - parts_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: AUTO
    fields:
        description:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        qty:
            type: decimal
            nullable: true
            precision: 10
            scale: 2
            comment: 'Positive is normal for sales invoices, negative for vendor invoices.'
        allocated:
            type: decimal
            nullable: true
            precision: 10
            scale: 2
            comment: "Number of allocated items, negative relative to qty.\nWhen qty + allocated = 0, then the item is fully used for purposes of COGS \ncalculations."
        sellprice:
            type: decimal
            nullable: true
            precision: 10
            scale: 2
            comment: ''
        fxsellprice:
            type: decimal
            nullable: true
            precision: 10
            scale: 2
            comment: ''
        discount:
            type: decimal
            nullable: true
            precision: 10
            scale: 2
            comment: ''
        assemblyitem:
            type: boolean
            nullable: true
            comment: ''
            default: false
        unit:
            type: string
            nullable: true
            length: null
            fixed: false
            comment: ''
        deliverydate:
            type: date
            nullable: true
            comment: ''
        serialnumber:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        vendorSku:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: vendor_sku
        notes:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        sortOrder:
            type: integer
            nullable: true
            column: sort_order
            options:
                unsigned: true
                default: 0
        active:
            type: boolean
            options:
                default: 1
        createDate:
            type: datetime
            column: create_date
        lastModifiedDate:
            type: datetime
            nullable: true
            column: last_modified_date
        inactiveDate:
            type: datetime
            nullable: true
            column: inactive_date
    oneToMany:
        invoiceNotes:
            targetEntity: InvoiceNote
            mappedBy: invoice
            orphanRemoval: true
    manyToOne:
        parts:
            targetEntity: Parts
            cascade: ["persist"]
            inversedBy: invoices
            joinColumns:
                parts_id:
                    referencedColumnName: id
            orphanRemoval: false
        transaction:
            targetEntity: Transaction
            cascade: ["persist"]
            inversedBy: invoices
            joinColumns:
                transaction_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: 
        prePersist: [ onPrePersist ]
        postPersist: [ onPostPersist ]
