#   Individuals seeking to add new location classes should coordinate with others.
Morus\AcceticBundle\Entity\LocationClass:
    type: entity
    table: accetic_location_class
    uniqueConstraints:
        location_class_id_key:
            columns:
                - id
                - control_code
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            generator:
                strategy: AUTO
    fields:
        controlCode:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: control_code
        class:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        description:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        sortOrder:
            type: integer
            nullable: true
            column: sort_order
            options:
                unsigned: true
                default: 0
        active:
            type: boolean
            options:
                default: 1
        createDate:
            type: datetime
            column: create_date
        lastModifiedDate:
            type: datetime
            nullable: true
            column: last_modified_date
        inactiveDate:
            type: datetime
            nullable: true
            column: inactive_date
    oneToMany:
        locations:
            targetEntity: Location
            mappedBy: locationClass
            orphanRemoval: false
            cascade: ["persist"]
    lifecycleCallbacks: 
        prePersist: [ onPrePersist ]
        postPersist: [ onPostPersist ]
