#   This table stores addresses, such as shipto and bill to addresses.
Morus\AcceticBundle\Entity\Location:
    type: entity
    table: accetic_location
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            generator:
                strategy: AUTO
        unit_id:
            associationKey: true
        location_class_id:
            associationKey: true
    fields:
        address:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        lineOne:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: line_one
        lineTwo:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: line_two
        lineThree:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: line_three
        city:
            type: string
            nullable: true
            length: 500
            fixed: false
            comment: ''
        state:
            type: string
            nullable: true
            length: 500
            fixed: false
            comment: ''
        zipCode:
            type: string
            nullable: true
            length: 80
            fixed: false
            comment: ''
            column: zip_code
        country:
            type: string
            nullable: true
            length: 500
            fixed: false
            comment: ''
        attention:
            type: string
            nullable: true
            length: 800
            fixed: false
            comment: ''
        sortOrder:
            type: integer
            nullable: true
            column: sort_order
            options:
                unsigned: true
                default: 0
        active:
            type: boolean
            options:
                default: 1
        createDate:
            type: datetime
            column: create_date
        lastModifiedDate:
            type: datetime
            nullable: true
            column: last_modified_date
        inactiveDate:
            type: datetime
            nullable: true
            column: inactive_date
    manyToOne:
        unit:
            targetEntity: Unit
            cascade: ["persist"]
            inversedBy: locations
            joinColumns:
                unit_id:
                    referencedColumnName: id
            orphanRemoval: false
        locationClass:
            targetEntity: LocationClass
            cascade: ["persist"]
            inversedBy: locations
            joinColumns:
                location_class_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: 
        prePersist: [ onPrePersist ]
        postPersist: [ onPostPersist ]
