Morus\AcceticBundle\Entity\P:
    type: mappedSuperclass
    table: accetic_p
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: AUTO
    fields:
        description:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
    oneToMany:
        cs:
            targetEntity: C
            mappedBy: p
            orphanRemoval: true
    lifecycleCallbacks: 
        prePersist: [ onPrePersist ]
        postPersist: [ onPostPersist ]
