#   This stores detail information about goods and services.  The type of part
#   is currently defined according to the following rules:
#   * If assembly is true, then an assembly
#   * If inventory_accno_id, income_accno_id, and expense_accno_id are not null then a part.
#   * If inventory_accno_id is null but the other two are not, then a service.
#   * Otherwise, a labor/overhead entry.
Morus\AcceticBundle\Entity\Parts:
    type: mappedSuperclass
    table: accetic_parts
#    indexes:
#        IDX_returns_accno_id:
#            columns:
#                - returns_accno_id
#        IDX_expense_accno_id:
#            columns:
#                - expense_accno_id
#        IDX_income_accno_id:
#            columns:
#                - income_accno_id
#        IDX_inventory_accno_id:
#            columns:
#                - inventory_accno_id
    uniqueConstraints:
        parts_itemcode_index_u:
            columns:
                - itemcode
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: AUTO
    fields:
        itemcode:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        itemname:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
        unit:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        forsale:
            type: boolean
            nullable: true
            comment: ''
            default: false
        listprice:
            type: decimal
            nullable: true
            precision: 10
            scale: 2
            comment: ''
        sellprice:
            type: decimal
            nullable: true
            precision: 10
            scale: 2
            comment: ''
        saleDescription:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: sale_description
        forpurchase:
            type: boolean
            nullable: true
            comment: ''
            default: false
        lastcost:
            type: decimal
            nullable: true
            precision: 10
            scale: 2
            comment: ''
        purchaseDescription:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: purchase_description
        priceupdate:
            type: date
            nullable: true
            comment: ''
            default: now
        weight:
            type: decimal
            nullable: true
            precision: 10
            scale: 2
            comment: ''
        onhand:
            type: decimal
            nullable: true
            precision: 10
            scale: 2
            comment: ''
            default: '0'
        notes:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        makemodel:
            type: boolean
            nullable: true
            comment: ''
            default: false
        assembly:
            type: boolean
            nullable: true
            comment: ''
            default: false
        alternate:
            type: boolean
            nullable: true
            comment: ''
            default: false
        rop:
            type: decimal
            nullable: true
            precision: 10
            scale: 2
            comment: 'Re-order point.  Used to select parts for short inventory report.'
        bin:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'Text identifier for where a part is stored.'
        obsolete:
            type: boolean
            nullable: true
            comment: ''
            default: false
        bom:
            type: boolean
            nullable: true
            comment: 'Show on Bill of Materials.'
            default: false
        image:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'Hyperlink to product image.'
        drawing:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        microfiche:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        partsgroupId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: partsgroup_id
        avgcost:
            type: decimal
            nullable: true
            precision: 10
            scale: 2
            comment: ''
        sortOrder:
            type: integer
            nullable: true
            column: sort_order
            options:
                unsigned: true
                default: 0
        active:
            type: boolean
            options:
                default: 1
        createDate:
            type: datetime
            column: create_date
        lastModifiedDate:
            type: datetime
            nullable: true
            column: last_modified_date
        inactiveDate:
            type: datetime
            nullable: true
            column: inactive_date
    oneToMany:
        invoices:
            targetEntity: Invoice
            mappedBy: parts
            orphanRemoval: true
#    manyToOne:
#        returnsAccno:
#            targetEntity: Account
#            cascade: ["persist"]
#            mappedBy: null
#            inversedBy: null
#            joinColumns:
#                returns_accno_id:
#                    referencedColumnName: id
#            orphanRemoval: false
#        expenseAccno:
#            targetEntity: Account
#            cascade: ["persist"]
#            mappedBy: null
#            inversedBy: null
#            joinColumns:
#                expense_accno_id:
#                    referencedColumnName: id
#            orphanRemoval: false
#        incomeAccno:
#            targetEntity: Account
#            cascade: ["persist"]
#            mappedBy: null
#            inversedBy: null
#            joinColumns:
#                income_accno_id:
#                    referencedColumnName: id
#            orphanRemoval: false
#        inventoryAccno:
#            targetEntity: Account
#            cascade: ["persist"]
#            mappedBy: null
#            inversedBy: null
#            joinColumns:
#                inventory_accno_id:
#                    referencedColumnName: id
#            orphanRemoval: false
            
    lifecycleCallbacks: 
        prePersist: [ onPrePersist ]
        postPersist: [ onPostPersist ]
