#   Every person, must have an unit to derive a common or display name. The correct way to get class information on a person would be person.unit_id->unit_class_to_unit.unit_id.
Morus\AcceticBundle\Entity\Person:
    type: entity
    table: accetic_person
    indexes:
#        IDX_salutation_id:
#            columns:
#                - salutation_id
    uniqueConstraints:
        person_id_key:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: AUTO
    fields:
        isPrimary:
            type: boolean
            options:
                default: 0
        firstName:
            type: string
            nullable: true
            length: 200
            fixed: false
            comment: ''
            column: first_name
        middleName:
            type: string
            nullable: true
            length: 200
            fixed: false
            comment: ''
            column: middle_name
        lastName:
            type: string
            nullable: true
            length: 200
            fixed: false
            comment: ''
            column: last_name
        birthdate:
            type: date
            nullable: true
            comment: ''
        personalId:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: personal_id
        sortOrder:
            type: integer
            nullable: true
            column: sort_order
            options:
                unsigned: true
                default: 0
        active:
            type: boolean
            options:
                default: 1
        createDate:
            type: datetime
            column: create_date
        lastModifiedDate:
            type: datetime
            nullable: true
            column: last_modified_date
        inactiveDate:
            type: datetime
            nullable: true
            column: inactive_date
    manyToOne:
#        salutation:
#            targetEntity: Salutation
#            cascade: ["persist"]
#            inversedBy: persons
#            joinColumns:
#                salutation_id:
#                    referencedColumnName: id
#            orphanRemoval: false
        unit:
            targetEntity: Unit
            cascade: ["persist"]
            inversedBy: persons
            joinColumns:
                unit_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        contacts:
            targetEntity: Contact
            mappedBy: person
            orphanRemoval: true
            cascade: ["persist"]
    lifecycleCallbacks: 
        prePersist: [ onPrePersist ]
        postPersist: [ onPostPersist ]
