#   The primary unit table to map to all contacts
Morus\AcceticBundle\Entity\Unit:
    type: mappedSuperclass
    table: accetic_unit
    indexes:
        IDX_account_number:
            columns:
                - account_number
    uniqueConstraints:
        unit_id_key:
            columns:
                - id
        unit_account_number_key:
            columns:
                - account_number
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: AUTO
    fields:
        accountNumber:
            type: string
            nullable: true
            length: 200
            fixed: false
            comment: ''
            column: account_number
        name:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'This is the common name of an unit. If it was a person it may be Joshua Drake, a company Acme Corp. You may also choose to use a domain such as commandprompt.com '
        sortOrder:
            type: integer
            nullable: true
            column: sort_order
            options:
                unsigned: true
                default: 0
        active:
            type: boolean
            options:
                default: 1
        createDate:
            type: datetime
            column: create_date
        lastModifiedDate:
            type: datetime
            nullable: true
            column: last_modified_date
        inactiveDate:
            type: datetime
            nullable: true
            column: inactive_date
    oneToMany:
        contacts:
            targetEntity: Contact
            mappedBy: unit
            orphanRemoval: true
            cascade: ["persist"]
        persons:
            targetEntity: Person
            mappedBy: unit
            orphanRemoval: true
            cascade: ["persist"]
        locations:
            targetEntity: Location
            mappedBy: unit
            orphanRemoval: true
            cascade: ["persist"]
        transactions:
            targetEntity: Transaction
            mappedBy: unit
            orphanRemoval: true
            cascade: ["persist"]
        ars:
            targetEntity: Ar
            mappedBy: unit
            orphanRemoval: true
            cascade: ["persist"]
        aps:
            targetEntity: Ap
            mappedBy: unit
            orphanRemoval: true
            cascade: ["persist"]
    manyToMany:
        unitClasses:
            targetEntity: UnitClass
            cascade: ["persist"]
            joinTable:
                name: accetic_units_to_unit_classes
                joinColumns:
                    unit_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    unit_class_id:
                        referencedColumnName: id
            orphanRemoval: false
#    manyToOne:
#        country:
#            targetEntity: Country
#            cascade: ["persist"]
#            mappedBy: null
#            inversedBy: null
#            joinColumns:
#                country_id:
#                    referencedColumnName: id
#            orphanRemoval: false
#    manyToMany:
#        payrollDeductionType:
#            targetEntity: PayrollDeductionType
#            cascade: ["persist"]
#            mappedBy: null
#            inversedBy: unit
#            joinTable:
#                name: payroll_deduction
#                joinColumns:
#                    -
#                        name: unit_id
#                        referencedColumnName: id
#                inverseJoinColumns:
#                    -
#                        name: payroll_deduction_type_id
#                        referencedColumnName: id
#            orderBy: null
#        type:
#            targetEntity: PayrollIncomeType
#            cascade: ["persist"]
#            mappedBy: null
#            inversedBy: unit
#            joinTable:
#                name: payroll_wage
#                joinColumns:
#                    -
#                        name: unit_id
#                        referencedColumnName: id
#                inverseJoinColumns:
#                    -
#                        name: type_id
#                        referencedColumnName: id
#            orderBy: null
    lifecycleCallbacks: 
        prePersist: [ onPrePersist ]
        postPersist: [ onPostPersist ]
