services:
    # Entity Services 
    morus_accetic.entity_manager:
        class: Morus\AcceticBundle\Model\EntityManager
        arguments: ['@doctrine.orm.entity_manager', '@service_container']
    
    # Form Services
    morus_accetic.form.type.unit:
        class: Morus\AcceticBundle\Form\Type\UnitType
        tags:
            - { name: form.type, alias: accetic_unit }
            
    morus_accetic.form.type.person:
        class: Morus\AcceticBundle\Form\Type\PersonType
        tags:
            - { name: form.type, alias: accetic_person }
    
    morus_accetic.form.type.contact:
        class: Morus\AcceticBundle\Form\Type\ContactType
        tags:
            - { name: form.type, alias: accetic_contact }
    
    morus_accetic.form.type.location:
        class: Morus\AcceticBundle\Form\Type\LocationType
        tags:
            - { name: form.type, alias: accetic_location }

    morus_accetic.form.type.ar.transaction:
        class: Morus\AcceticBundle\Form\Type\ArTransactionType
        tags:
            - { name: form.type, alias: accetic_ar_transaction }
            
    morus_accetic.form.type.ar:
        class: Morus\AcceticBundle\Form\Type\ArType
        tags:
            - { name: form.type, alias: accetic_ar }
    
    morus_accetic.form.type.invoices:
        class: Morus\AcceticBundle\Form\Type\InvoicesType
        tags:
            - { name: form.type, alias: accetic_invoices }
            
    morus_accetic.form.type.invoice:
        class: Morus\AcceticBundle\Form\Type\InvoiceType
        tags:
            - { name: form.type, alias: accetic_invoice }
    morus_accetic.form.type.parts:
        class: Morus\AcceticBundle\Form\Type\PartsType
        tags:
            - { name: form.type, alias: accetic_parts }

    morus_accetic.form.type.parts_list:
        class: Morus\AcceticBundle\Form\Type\PartsListType
        tags:
            - { name: form.type, alias: accetic_parts_list }