<?php

namespace Morus\AcceticBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PartsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartsRepository extends EntityRepository
{
    public function findByIds($ids)
    {
        $query = $this->createQueryBuilder('p')
                ->addSelect('p')
                ->where('p.id IN(:ids)')
                ->setParameter('ids', array_values($ids))
                ->getQuery();
        
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    
    public function findOneByItemname($itemname)
    {
        $query = $this->getEntityManager()
                ->createQuery(
                        'SELECT pe '
                        . 'FROM MorusFasBundle:PartsExt pe '
                        . 'JOIN pe.parts p '
                        . 'WHERE p.itemname = :itemname '
                        )
                ->setParameter('itemname', $itemname)
                ;
        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
