<?php

namespace Morus\AcceticBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PartsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartsRepository extends EntityRepository
{
    public function findByIds($ids)
    {
        $query = $this->createQueryBuilder('p')
                ->addSelect('p')
                ->where('p.id IN(:ids)')
                ->setParameter('ids', array_values($ids))
                ->getQuery();
        
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
