<?php

namespace Morus\AcceticBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitRepository extends EntityRepository
{
    
    public function findListByControlCode($controlCode)
    {
        $query = $this->getEntityManager()
                ->createQuery(
                        'SELECT e.id, e.name, '
    
                        . '(SELECT pc.description '
                        . 'FROM MorusAcceticBundle:Person p '
                        . 'JOIN p.contacts pc '
                        . 'JOIN pc.contactClass pcc '
                        . 'WHERE p.unit = e AND p.isPrimary = 1 and pcc.controlCode = \'EMAIL\') as email, '
                        
                        . '(SELECT c.description '
                        . 'FROM MorusAcceticBundle:Contact c '
                        . 'JOIN c.contactClass cc '
                        . 'WHERE cc.controlCode = \'PRIMARY_TELEPHONE\' AND c.unit = e ) as telephone '
                        
                        . 'FROM MorusAcceticBundle:Unit e '
                        . 'JOIN e.unitClasses ec '
                        . 'WHERE ec.controlCode = :controlCode '
                        )
                ->setParameter('controlCode', $controlCode);
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    
    public function findAllList()
    {
        $query = $this->getEntityManager()
                ->createQuery(
                        'SELECT e.id, e.name, '
                        
                        . '(SELECT pc.description '
                        . 'FROM MorusAcceticBundle:Person p '
                        . 'JOIN p.contacts pc '
                        . 'JOIN pc.contactClass pcc '
                        . 'WHERE p.unit = e AND p.isPrimary = 1 and pcc.controlCode = \'EMAIL\') as email, '
                        
                        . '(SELECT c.description '
                        . 'FROM MorusAcceticBundle:Contact c '
                        . 'JOIN c.contactClass cc '
                        . 'WHERE cc.controlCode = \'PRIMARY_TELEPHONE\' AND c.unit = e ) as telephone '
                        
                        . 'FROM MorusAcceticBundle:Unit e '
                        );
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}