morus_accetic_contacts:
    path:     /
    defaults: { _controller: "MorusAcceticBundle:Contacts:index"}

morus_accetic_contacts_list:
    path:     /{ecc}/list
    defaults: { _controller: "MorusAcceticBundle:Contacts:listAjax", ecc: "All" }

morus_accetic_contacts_show:
    path:     /{id}/show
    defaults: { _controller: "MorusAcceticBundle:Contacts:show" }

morus_accetic_contacts_new:
    path:     /{ecc}/new
    defaults: { _controller: "MorusAcceticBundle:Contacts:new", ecc: "All" }
    
morus_accetic_contacts_create:
    path:     /{ecc}/create
    defaults: { _controller: "MorusAcceticBundle:Contacts:create", ecc: "All" }
    requirements: { _method: post }

morus_accetic_contacts_edit:
    path:     /{id}/edit
    defaults: { _controller: "MorusAcceticBundle:Contacts:edit" }

morus_accetic_contacts_update:
    path:     /{id}/update
    defaults: { _controller: "MorusAcceticBundle:Contacts:update" }
    requirements: { _method: post|put }

morus_accetic_contacts_delete:
    path:     /{id}/delete
    defaults: { _controller: "MorusAcceticBundle:Contacts:delete" }
    requirements: { _method: post|delete }
